language: objective-c
osx_image: xcode6.4
xcode_workspace: "I Bike CPH/I Bike CPH.xcworkspace"
xcode_scheme: "I Bike CPH"
podfile: "I Bike CPH/Podfile"
env:
  global:
  - app_name="I Bike CPH"
  - prov_profile_name="ibikecph_ad_hoc"
  - 'developer_name="iPhone Distribution: Socialsquare ApS (SP46WFGATT)"'
  - secure: fLkpILcvsjBRzBEIMpBe2/dEYxTBCS4zHoGZ/0g98NHeI41tG/NQuvWz9VlImWO/g3SqtVcAw+Z7UGJoEEjXyQ9m0Y+uwPa7sYPeb8QK5c8NQOz6jTOKSMN7xam5x59cBO6QqYTuJEyb8ODtssb3Evm4hQDfpPRPSZ4kt2/a80g=
  - secure: qsyGczDbFlP0OGg1OUyYclaTAmtMc9+f7DL6St6FuH3uFeVP+Fz0mkE2UdvV8ewndG82Z/UGqlj+A7EytaRalffKzzQfw7AP+im0Wn+r3lxeU1IjY3t//4MRK9JMwQZCuG6H/29jD3udV+VJryij0th8uU6O0LDz0FaDW4tSnu4=
before_install:
- "./scripts/decrypt-secrets.sh"
- "./scripts/copy-plists.sh"
before_script:
- "./scripts/add-key.sh"
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
notifications:
  slack:
    secure: w8+eX+RCiNvZ4iA1M2mY5dGAqHvnBaE77Jw68JFspg1eJAQsiq1rQDZnWhgZbSZSflEXUuPE0pkMrOGBGrSZ+npx3UnwX17voy7E/Zl7RBWYJzfNmn6gtnEzieWWL4IW43o2Ep/k1UvJLBw9kQzJYjT1BXlY+oMJYhT/MZty2xI=
