language: objective-c
osx_image: xcode6.4
xcode_workspace: 'I Bike CPH/I Bike CPH.xcworkspace'
xcode_scheme: 'CykelPlanen'
podfile: 'I Bike CPH/Podfile'

# before_script:
# - ./scripts/travis/add-key.sh
# after_script:
# - ./scripts/travis/remove-key.sh
# after_success:
# - ./scripts/travis/testflight.sh

env:
  global:
  - APPNAME=CykelPlanen
#   - 'DEVELOPER_NAME="iPhone Distribution: NAME_OF_THE_DEVELOPER (CODE)"'
#   - PROFILE_UUID=PROVISIONING_PROFILE_UUID

notifications:
  slack:
    secure: w8+eX+RCiNvZ4iA1M2mY5dGAqHvnBaE77Jw68JFspg1eJAQsiq1rQDZnWhgZbSZSflEXUuPE0pkMrOGBGrSZ+npx3UnwX17voy7E/Zl7RBWYJzfNmn6gtnEzieWWL4IW43o2Ep/k1UvJLBw9kQzJYjT1BXlY+oMJYhT/MZty2xI=
