language: objective-c
osx_image: xcode6.4
podfile: I Bike CPH/Podfile
env:
  global:
  - APP_NAME_0="ibikecph"
  - APP_NAME_1="cykelplanen"
  - SCHEME_NAME_0="I Bike CPH"
  - SCHEME_NAME_1="CykelPlanen"
  - WORKSPACE_NAME_0="I Bike CPH/I Bike CPH.xcworkspace"
  - WORKSPACE_NAME_1="I Bike CPH/I Bike CPH.xcworkspace"
  - PROV_PROFILE_NAME_0="ibikecph_distribution"
  - PROV_PROFILE_NAME_1="ibikecph_distribution"
  - 'CODE_SIGNING_IDENTITY="iPhone Distribution: Socialsquare ApS"'
  - PROVISIONING_PROFILE_0="$HOME/Library/MobileDevice/Provisioning Profiles/$PROV_PROFILE_NAME_0.mobileprovision"
  - PROVISIONING_PROFILE_1="$HOME/Library/MobileDevice/Provisioning Profiles/$PROV_PROFILE_NAME_1.mobileprovision"
  - OUTPUTDIR="$PWD/build"
  - SDK="iphoneos8.4"
  - FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1
  - secure: wK2B3GeLZ62OOrFot6JfTto5d6qp/+8KwcaAVxahinBfDjMsmG04C9mtCXApEDVzLzuLv0IK9vjnLTXLvyaS6htSUfBfEQsOWkDgRMEnPxQDqv4fqD3F6ImNOYjh3XtgurSUZvhg5c59HYP62CjWYcDQTbN2LDaCJjUAo3whLrc=
  - secure: MeCVPr8Nr/Cb5bh5/2eIy9EDYmtXmBhpfNLQk420BRoMFto/qPp1Gl9EENApscUukqDET7iDiuehCQhOF2qs+n6glSsuRQNvPAM44s5l1f9bqnWVeCKTG7lbNtUsaPn/6lPXHEDFFz6ONOlJxW2H3tnIaVI1V1QFtR601YBFR6s=
  - secure: 1+wppINsT52gDO3crwNl6c/e3q3cfdktx3BTj0kATXFAtmPSXOHLdOv5HQmmr5dV3mA4MAg6u2fsGFE7UzizRdmxeAtrqCaRmlEhzoyL0fgeTkGKXqY/U7AG1geNOFcp/GtIcCSKFt3/DIQcjRvEahj0MWZV+xhdCD8FxIPewvg=
  - secure: ufu97qJ9d+eTTKaoVxOjJnFLLlZ+KRqXvjbibHGOx0So0SnydKx3jBr/uPZ4YxiNu1M0fjNZK8+Ir1H01FgoXKmGQEKZvonI5ATPCvv30YNRiTMl1O5u2qyyhI0Mwtz2uVtCqANC7wGrp6+0i+ovYS2plRh2w/YbuIJLfNkfX50=
before_install:
- gem install deliver
- gem install gym
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/certs/distribution.cer.enc
  -out secrets/ios/certs/distribution.cer -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/certs/distribution.p12.enc
  -out secrets/ios/certs/distribution.p12 -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/certs/development.cer.enc
  -out secrets/ios/certs/development.cer -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/certs/development.p12.enc
  -out secrets/ios/certs/development.p12 -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/profile/ibikecph_distribution.mobileprovision.enc
  -out secrets/ios/profile/ibikecph_distribution.mobileprovision -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/profile/cykelplanen_distribution.mobileprovision.enc
  -out secrets/ios/profile/cykelplanen_distribution.mobileprovision -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/shared/smroute_settings_private.plist.enc
  -out secrets/ios/shared/smroute_settings_private.plist -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/ibikecph/smroute_settings_app_private.plist.enc
  -out secrets/ios/ibikecph/smroute_settings_app_private.plist -d
- openssl aes-256-cbc -k "$FILE_ENC_PASSWORD" -in secrets/ios/cykelplanen/smroute_settings_app_private.plist.enc
  -out secrets/ios/cykelplanen/smroute_settings_app_private.plist -d
- "./ci_scripts/copy_plists.sh"
before_script:
- "./ci_scripts/add_keys.sh"
script:
- gym -w "$WORKSPACE_NAME_0" -s "$SCHEME_NAME_0" -o "$OUTPUTDIR" -n "$APP_NAME_0" -i "$CODE_SIGNING_IDENTITY"
  -e "$PROVISIONING_PROFILE_0" -k "$SDK"
- gym -w "$WORKSPACE_NAME_1" -s "$SCHEME_NAME_1" -o "$OUTPUTDIR" -n "$APP_NAME_1" -i "$CODE_SIGNING_IDENTITY"
  -e "$PROVISIONING_PROFILE_1" -k "$SDK"
after_success:
- "./ci_scripts/push_to_testflight.sh"
after_script:
- "./ci_scripts/remove_keys.sh"
notifications:
  slack:
    secure: w8+eX+RCiNvZ4iA1M2mY5dGAqHvnBaE77Jw68JFspg1eJAQsiq1rQDZnWhgZbSZSflEXUuPE0pkMrOGBGrSZ+npx3UnwX17voy7E/Zl7RBWYJzfNmn6gtnEzieWWL4IW43o2Ep/k1UvJLBw9kQzJYjT1BXlY+oMJYhT/MZty2xI=
