source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

link_with 'I Bike CPH', 'CykelPlanen'

inhibit_all_warnings!

pod 'GoogleAnalytics-iOS-SDK', '~>3.10'
pod 'TTTAttributedLabel', '~>1.10'
pod 'DAKeyboardControl', '~>2.0'
pod 'UIImage-Categories'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
