platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

abstract_target 'app_target' do

  pod 'TTTAttributedLabel', '~> 2.0'
  pod 'DAKeyboardControl', '~> 2.4'
  pod 'UIImage-Categories', '~> 1.0'
  pod 'PSTAlertController', '1.1.0'
  pod 'Realm', '~> 0.99.0'
  pod 'Mapbox-iOS-SDK', '1.6.0'
  pod 'NibDesignable', '~> 2.3'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'ORStackView',  '~> 3.0'
  pod 'Crashlytics', '~> 3.7.0'
  pod 'SwiftyUserDefaults', '~> 2.2.0'
  pod 'SwiftHEXColors', '~> 1.0'
  pod 'SnapKit', '~> 0.21.0'
  pod 'AsyncSwift', '~> 2.0.4'
  pod 'FBSDKLoginKit', '~> 4.33.0'

  target 'I Bike CPH'
  target 'CykelPlanen'

end

abstract_target 'test_target' do

  pod 'OCMockito', '~> 1.0'

  target 'I Bike CPHTests'
  target 'CykelPlanenTests'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        config.build_settings['ENABLE_BITCODE'] = "NO"
    end
  end

  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
