source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

link_with 'I Bike CPH', 'CykelPlanen'

use_frameworks!
inhibit_all_warnings!

pod 'GoogleAnalytics-iOS-SDK', '~>3.10'
pod 'TTTAttributedLabel', '~>1.13'
pod 'DAKeyboardControl', '~>2.4'
pod 'UIImage-Categories', '~>1.0'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'PSTAlertController', '1.1.0'
pod 'Realm', '0.95.0'
pod 'Mapbox-iOS-SDK', '1.6.0'
pod 'NibDesignable', '~>1.1.0'
pod 'ORStackView',  '~>3.0'
pod 'Fabric'
pod 'Crashlytics'

target :CykelPlanenTests, :exclusive => true do
    pod 'OCMockito', '~> 1.0'
end
target :'I Bike CPHTests', :exclusive => true do
    pod 'OCMockito', '~> 1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
